language: python
sudo: false
dist: xenial
cache: pip

env:
  global:
    - PYTHONFAULTHANDLER=x
    - SKIP_LATEX_BUILD=1
    - IS_PYTHON=true

matrix:
  include:
    - python: '3.5'
      env:
        - TOXENV=du12
    - python: '3.6'
      env:
        - TOXENV=du13
    - python: '3.7'
      env:
        - TOXENV=du14
    - python: '3.8'
      env:
        - TOXENV=du15
        - PYTEST_ADDOPTS="--cov ./ --cov-append --cov-config setup.cfg"
    - python: 'nightly'
      env: TOXENV=py38
    - python: '3.6'
      env: TOXENV=docs
    - python: '3.6'
      env: TOXENV=docslint
    - python: '3.6'
      env: TOXENV=mypy
    - python: '3.6'
      env: TOXENV=flake8

    - language: node_js
      node_js:
        - 10.7
      env: IS_PYTHON=false
      services: xvfb

install:
  - "sudo apt-get install graphviz"
  - if [ $IS_PYTHON = true ]; then pip install -U tox codecov; fi
  - if [ $IS_PYTHON = false ]; then npm install; fi

script:
  - if [ $IS_PYTHON = true ]; then tox -- -v; fi
  - if [ $IS_PYTHON = false ]; then npm test; fi

after_success:
  - if [[ -e .coverage ]]; then codecov -e $TOXENV; fi
