language: python
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "pypy-5.4.1"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "nightly"
env:
  global:
    - TEST='-v --durations 25'
    - PYTHONFAULTHANDLER=x
    - PYTHONWARNINGS=all
  matrix:
    - DOCUTILS=0.12
    - DOCUTILS=0.13.1
matrix:
  exclude:
    - python: "3.4"
      env: DOCUTILS=0.12
    - python: "3.5"
      env: DOCUTILS=0.12
    - python: nightly
      env: DOCUTILS=0.12
    - python: "pypy-5.4.1"
      env: DOCUTILS=0.12
addons:
  apt:
    packages:
    - graphviz
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-xetex
    - lmodern
install:
  - pip install -U pip setuptools
  - pip install docutils==$DOCUTILS
  - pip install -r test-reqs.txt
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then python3.6 -m pip install mypy 'typed-ast<1.0'; fi
script:
  - flake8
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then make style-check type-check test-async; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '3.6' ]]; then make test; fi
