language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
env:
  global:
    - TEST='-v --durations=25'
    - PYTHONFAULTHANDLER=x
    - PYTHONWARNINGS=all
  matrix:
    - DOCUTILS=0.12
    - DOCUTILS=0.13.1
addons:
  apt:
    packages:
    - graphviz
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-xetex
    - lmodern
install:
  - pip install -U pip setuptools
  - pip install docutils==$DOCUTILS
  - pip install -r test-reqs.txt
before_script:
  -  if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then flake8; fi
script:
  -  if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then make style-check test-async; fi
  -  if [[ $TRAVIS_PYTHON_VERSION != '3.5' ]]; then make test; fi
