language: python
sudo: false
dist: trusty
cache: pip

env:
  global:
    - PYTHONFAULTHANDLER=x
    - SKIP_LATEX_BUILD=1
    - IS_PYTHON=true

matrix:
  include:
    - python: 'pypy'
      env: TOXENV=pypy
    - python: '2.7'
      env:
        - TOXENV=du13
        - PYTEST_ADDOPTS="--cov ./ --cov-append --cov-config setup.cfg"
    - python: '3.4'
      env: TOXENV=py34
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env:
        - TOXENV=py36
        - PYTEST_ADDOPTS="--cov ./ --cov-append --cov-config setup.cfg"
    - python: '3.7'
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: 'nightly'
      env: TOXENV=py38
      dist: xenial
      sudo: true
    - python: '3.6'
      env: TOXENV=docs
    - python: '3.6'
      env: TOXENV=mypy
    - python: '3.6'
      env: TOXENV=flake8

    - language: node_js
      node_js:
        - 10.7
      env: IS_PYTHON=false
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

install:
  - if [ $IS_PYTHON = true ]; then pip install -U tox codecov; fi
  - if [ $IS_PYTHON = false ]; then npm install; fi

script:
  - if [ $IS_PYTHON = true ]; then tox -- -v; fi
  - if [ $IS_PYTHON = false ]; then npm test; fi

after_success:
  - if [[ -e .coverage ]]; then codecov -e $TOXENV; fi
