language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
env:
  - DOCUTILS=0.10
  - DOCUTILS=0.11
  - DOCUTILS=0.12
install:
  - pip install docutils==$DOCUTILS
  - pip install -r test-reqs.txt
script: make test
