version: 2
jobs:
  build:
    docker:
      - image: sphinxdoc/docker-ci
        environment:
          DO_EPUBCHECK: 1
    working_directory: /sphinx
    steps:
      - checkout
      - run: /python3.8/bin/pip install -U pip setuptools
      - run: /python3.8/bin/pip install -U .[test]
      - run: mkdir -p test-reports/pytest
      - run: make test PYTHON=/python3.8/bin/python TEST="--junitxml=test-reports/pytest/results.xml -vv"
      - store_test_results:
          path: test-reports
