name: CI (LaTeX)

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test on LaTeX image
    container:
      image: ghcr.io/sphinx-doc/sphinx-ci
    env:
      DO_EPUBCHECK: 1
    steps:
    - name: Alias python3 to python
      run: ln -s /usr/bin/python3 /usr/bin/python
    - uses: actions/checkout@v3
    - name: Check Python version
      run: python --version
    - name: Install dependencies
      run: pip install -U pip tox
    - name: Run Tox
      run: tox -e py -- -vv
