name: CI (LaTeX)

on: [push, pull_request]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test on LaTeX image
    container:
      image: ghcr.io/sphinx-doc/sphinx-ci
    env:
      DO_EPUBCHECK: "1"
    steps:
    - name: Alias python3 to python
      run: ln -s /usr/bin/python3 /usr/bin/python
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Check Python version
      run: python --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    - name: Install maven
      run: apt-get install maven -y
    - name: Test with pytest
      run: >
        python
        -X dev
        -X warn_default_encoding
        -m pytest
        -vv
        --color yes
        --durations 25
