name: Tests

on: [push, pull_request]

env:
  PYTHONFAULTHANDLER: x
  SKIP_LATEX_BUILD: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: ["py35", "py36", "py37", "py38", "nightly"]

        include:
          - name: "py35"
            python: "3.5"
            tox_env: "du12"

          - name: "py36"
            python: "3.6"
            tox_env: "du13"

          - name: "py37"
            python: "3.7"
            tox_env: "du14"

          - name: "3.8"
            python: "3.8"
            tox_env: "du15"
            use_coverage: true

          - name: "nightly"
            python: "3.10-dev"
            tox_env: "du16"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        if: matrix.python != '3.10-dev'
        with:
          python-version: ${{ matrix.python }}
      - name: Set up Python ${{ matrix.python }} (deadsnakes)
        uses: deadsnakes/action@v1.0.0
        if: matrix.python == '3.10-dev'
        with:
          python-version: ${{ matrix.python }}

      - name: Install graphviz
        run: sudo apt-get install graphviz

      - name: Run tests
        env:
          TOXENV: ${{ matrix.tox_env }}
        run: tox -- -vv

      - name: codecov
        if: matrix.use_coverage
        env:
          TOXENV: ${{ matrix.tox_env }}
        run: codecov -e $TOXENV
